### ISSUE TITLE
Require Term and Services html forms

### ISSUE THREAD

**Issue by raoasifraza11** [interpreter-zone/ani-motors#18]
Kindly write all terms and services in html form I will share all docs with you via email. It urget 🔢 👍 👎 

@hariskhurshid

**Comment by raoasifraza11** [comment]
@Ahmadkhan12345566 please share all docs with @hariskhurshid

**Comment by raoasifraza11** [comment]
@hariskhurshid should work in your branch

**Comment by hariskhurshid** [comment]
@raoasifraza11 hiii

**Comment by hariskhurshid** [comment]
:)

**Comment by hariskhurshid** [comment]
u their?

**Comment by raoasifraza11** [comment]
Yes

**Comment by hariskhurshid** [comment]
@Ahmadkhan12345566  qariii burshy 🥇

**Comment by hariskhurshid** [comment]
@raoasifraza11 contact me..whatsapp

**Comment by raoasifraza11** [comment]
Kindly, be quick @hariskhurshid we need its

**Comment by raoasifraza11** [comment]
Okay come

**Comment by hariskhurshid** [comment]
m their

**Comment by raoasifraza11** [comment]
@hariskhurshid I've problem with my phone kindly contact me on https://fsdevelopersteam.slack.com

**Comment by hariskhurshid** [comment]
@raoasifraza11  i  dont have an account

**Comment by hariskhurshid** [comment]
soo  tel me here

**Comment by hariskhurshid** [comment]
what's the task...

**Comment by raoasifraza11** [comment]
Okay wait a bit, and singup above url we need it later

**Comment by raoasifraza11** [comment]
@hariskhurshid any update times up!!!

**Comment by raoasifraza11** [comment]
Any update @hariskhurshid
